### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by BryanBerger98** [BryanBerger98/curriculum#1]
## 📄 Description

Set up project for preparing for development.

## ✅ Tasks
- [x] Create Next.js
- [x] Install dependencies
- [x] Set up ESLint
- [x] Set up Husky
