### ISSUE TITLE
Sign in user

### ISSUE THREAD

**Issue by BryanBerger98** [BryanBerger98/curriculum#2]
## 💬 User story
As user, I want to sign in to my account, so that I can edit my profile.

## 📄 Description
The user should be able to sign in using his credentials (email and password).

## ✅ Tasks
- [x] Create a sign in form
- [x] Create an API route to manage the sign in action:
  - [x] Verify if the user already exists
  - [x] Verify if the password matches the registered one
  - [x] Update the last authentication date of the user
  - [x] Set the authentication cookie in the response
  - [x] Redirect user to his profile page
