### ISSUE TITLE
Sign up user

### ISSUE THREAD

**Issue by BryanBerger98** [BryanBerger98/curriculum#3]
## 💬 Story

As a user, I want to sign up to the app so I can sign in to my account and use the app with a personalized experience.

## 📄 Description

The user should be able to sign up by filling a form which should require the following fields:
* First name
* Last name
* Email (Should be validated)
* Password (at least 8 chars)
* Confirm password
* Accept terms and conditions (checkbox)

On submitting, if there is no error, the user should be redirected to his dashboard page.

## ✅ Tasks
- [x] Create the form
- [x] Create a user table in the database
- [x] Configure Lucia Auth
- [x] Create an API route to handle the sign up workflow
- [x] Redirect the user to the dashboard
